# Generated by Django 4.0 on 2022-01-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECG', '0002_rename_doctor_patient_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='heartrate',
        ),
    ]
