# Generated by Django 4.0 on 2022-01-27 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ECG', '0003_remove_report_heartrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
