# Generated by Django 4.0 on 2022-01-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECG', '0004_report_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='telegramId',
        ),
        migrations.AddField(
            model_name='patient',
            name='sectionTelegramId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
